//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local TRUE, FALSE, NULL, ONTICK, ONDRAW, SWS = true, false, nil, &quot;onTick&quot;, &quot;onDraw&quot;, &quot;SWS&quot;
        ///
        ///local temp1, temp2, Current, Frames, Frame, halt, start, onTickRan, Stack, CallStack, sp, csp, Globals, Constants, hasOnTick, hasOnDraw, ProgramHex, ProgramStr, toNum, toStr, strChar, name = 0, 0, property.getNumber(SWS), {}, {}, FALSE, FALSE, FALSE, {}, {}, 0, 0, {}, {}, FALSE, FALSE, &quot;&quot;, &quot;&quot;, tonumber, tostring, string.char, &quot;&quot;
        ///
        ///local logInstructionFreq, logCallFreq = FALSE, FALSE
        ///local instructionStats, callSt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DebugVM {
            get {
                return ResourceManager.GetString("DebugVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local TRUE, FALSE, NULL, ONTICK, ONDRAW, SWS = true, false, nil, &quot;onTick&quot;, &quot;onDraw&quot;, &quot;SWS&quot;
        ///
        ///local temp1, temp2, Current, Frames, Frame, halt, start, onTickRan, Stack, CallStack, sp, csp, Globals, Constants, hasOnTick, hasOnDraw, ProgramHex, ProgramStr, toNum, toStr, strChar, name = 0, 0, property.getNumber(SWS), {}, {}, FALSE, FALSE, FALSE, {}, {}, 0, 0, {}, {}, FALSE, FALSE, &quot;&quot;, &quot;&quot;, tonumber, tostring, string.char, &quot;&quot;
        ///
        ///local logInstructionFreq, logCallFreq = FALSE, FALSE
        ///local instructionStats, callSt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FastVM {
            get {
                return ResourceManager.GetString("FastVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local s,o,w,Z,W,i,O=true,false,nil,&quot;onTick&quot;,&quot;onDraw&quot;,property,&quot;SWS&quot;local p,F,v,A,e,E,j,m,a,q,l,Q,I,H,L,K,J,R,n,x=0,0,i.getNumber(O),{},{},o,{},{},0,0,{},{},o,o,&quot;&quot;,&quot;&quot;,tonumber,tostring,string.char,&quot;&quot;for l=1,v do
        ///L=L..i.getText(O..l)end
        ///v=1
        ///function B(i,D)D=K:sub(v):find(n(1))if D then
        ///i=K:sub(v,v+D-2)v=v+D
        ///end
        ///return i or 0
        ///end
        ///function S(z,T,i)z=J(B())i=(z==2 and J(B())or B())if z&lt;1 then i=w
        ///elseif z==1 then i=i==O
        ///elseif z==4 then
        ///T={}i=J(i)for l=1,i do
        ///T[S()]=S()end
        ///i=T
        ///end
        ///return i
        ///end
        ///for l=1,#L,2 do
        ///K= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MinimizedVM {
            get {
                return ResourceManager.GetString("MinimizedVM", resourceCulture);
            }
        }
    }
}
